version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5433:5433
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5433 -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      polkanet:
        ipv4_address: 10.50.61.4
  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5433
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=PolkadotStandalone
      - --disable-historical=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      polkanet:
        ipv4_address: 10.50.61.5   
networks:
  polkanet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.61.0/24
          gateway: 10.50.61.1